#!/bin/bash -

# Copyright (c) 2019 Alan D. Salewski <salewski@att.net>
#
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301,, USA.

# mvn-get: Download a maven artifact (and its dependencies) from the command
# line. Uses the 'maven-dependencies-plugin' from the 'mvn' command line, so
# the downloaded artifacts are stored in the local ~/.m2/repository/ just as
# if they were specified as deps in a pom.xml of a built project.
#
#
# Usage:
#
#     mvn-get [OPTION...] groupId:artifactId:version[:type[:classifier]] [--] [MVN_OPTION...]
#
#
# Example:
#
#     $ mvn-get org.apache.avro:avro:1.8.2
#
#
# FIXME: This whole thing is just a rough sketch; don't believe the help
#        output -- none of the command line options yet work as advertized.
#
#
# Notes:
#
#     * The maven-dependency-plugin can be a little picky, especially older
#       versions (e.g. 2.1). Versions that are known to work with this
#       approach:
#           - 2.8
#           - 3.1.1
#

declare -r PROG='mvn-get'

# declare -r MAINTAINER='@PACKAGE_BUGREPORT@'  # value filtered-in at build time
declare -r MAINTAINER='Alan D. Salewski <salewski@att.net>'  # FIXME: filter-in at build time

# declare -r VERSION='@VERSION@'  # value filtered-in at build time
declare -r VERSION='0.0.1'  # FIXME: filter-in at build time



f_print_help () {

    cat <<EOF
usage: $PROG [OPTION...] MAVEN_ARTIFACT_COORDINATES [--] [MVN_OPTION...]

where MAVEN_ARTIFACT_COORDINATES has the form:

    groupId:artifactId:version[:type[:classifier]]

Downloads a maven artifact (and its dependencies) from the command line.

  -h, --help     Print this help message on stdout
  -V, --version  Print the version of the program on stdout

  -v, --verbose  Print program progress messages on stderr. Specify multiple
                   times to increase verbosity: info, debug, and tracing (set -x)

      --         Signals the end of options and disables further options processing. All
                   remaining arguments will be passed through to mvn(1)

Report bugs to $MAINTAINER.
EOF
}

f_print_version () {
    cat <<EOF
${PROG} ${gl_const_release}
Copyright (C) 2019 Alan D. Salewski
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Alan D. Salewski.
EOF
}


if test $# -lt 1; then
    printf "${PROG} (error): required MAVEN_ARTIFACT_COORDINATES not provided; bailing out\n" 1>&2
    f_print_help 1>&2
    exit 1
fi

_maven_artifact_coords=$1
shift

# Any remaining arguments will be passed-through "as is" to mvn

# XXX: It's wonky that we depend on the order of the command line arguments,
#      but this version of the program is just a rough sketch for my personal
#      use. A more productized future version might do something more
#      intelligent.

declare -a _my_mvn_opts=()

# _my_mvn_opts+=( 'org.apache.maven.plugins:maven-dependency-plugin:2.8:get' )
# _my_mvn_opts+=( 'org.apache.maven.plugins:maven-dependency-plugin:3.1.1get' )
_my_mvn_opts+=( 'org.apache.maven.plugins:maven-dependency-plugin:get' )

_my_mvn_opts+=( '-Dartifact='"${_maven_artifact_coords}" )

set -x
mvn "$@" "${_my_mvn_opts[@]}"
